/*
 * Gewinnquoten
 * Wir geben die Gewinnquoten aus 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@wbstraining.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package wbs.jsf1.rest.v1.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Spiel77
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-03-15T00:05:48.184+01:00")
public class Spiel77   {
  @JsonProperty("klasse")
  private String klasse = null;

  @JsonProperty("anzahlrichtige")
  private String anzahlrichtige = null;

  @JsonProperty("gewinne")
  private Long gewinne = null;

  @JsonProperty("quoten")
  private Long quoten = null;

  public Spiel77 klasse(String klasse) {
    this.klasse = klasse;
    return this;
  }

  /**
   * Get klasse
   * @return klasse
   **/
  @JsonProperty("klasse")
  @ApiModelProperty(value = "")
  public String getKlasse() {
    return klasse;
  }

  public void setKlasse(String klasse) {
    this.klasse = klasse;
  }

  public Spiel77 anzahlrichtige(String anzahlrichtige) {
    this.anzahlrichtige = anzahlrichtige;
    return this;
  }

  /**
   * Get anzahlrichtige
   * @return anzahlrichtige
   **/
  @JsonProperty("anzahlrichtige")
  @ApiModelProperty(value = "")
  public String getAnzahlrichtige() {
    return anzahlrichtige;
  }

  public void setAnzahlrichtige(String anzahlrichtige) {
    this.anzahlrichtige = anzahlrichtige;
  }

  public Spiel77 gewinne(Long gewinne) {
    this.gewinne = gewinne;
    return this;
  }

  /**
   * Get gewinne
   * @return gewinne
   **/
  @JsonProperty("gewinne")
  @ApiModelProperty(value = "")
  public Long getGewinne() {
    return gewinne;
  }

  public void setGewinne(Long gewinne) {
    this.gewinne = gewinne;
  }

  public Spiel77 quoten(Long quoten) {
    this.quoten = quoten;
    return this;
  }

  /**
   * Get quoten
   * @return quoten
   **/
  @JsonProperty("quoten")
  @ApiModelProperty(value = "")
  public Long getQuoten() {
    return quoten;
  }

  public void setQuoten(Long quoten) {
    this.quoten = quoten;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Spiel77 spiel77 = (Spiel77) o;
    return Objects.equals(this.klasse, spiel77.klasse) &&
        Objects.equals(this.anzahlrichtige, spiel77.anzahlrichtige) &&
        Objects.equals(this.gewinne, spiel77.gewinne) &&
        Objects.equals(this.quoten, spiel77.quoten);
  }

  @Override
  public int hashCode() {
    return Objects.hash(klasse, anzahlrichtige, gewinne, quoten);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Spiel77 {\n");
    
    sb.append("    klasse: ").append(toIndentedString(klasse)).append("\n");
    sb.append("    anzahlrichtige: ").append(toIndentedString(anzahlrichtige)).append("\n");
    sb.append("    gewinne: ").append(toIndentedString(gewinne)).append("\n");
    sb.append("    quoten: ").append(toIndentedString(quoten)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

